server:
  port: 8002
spring:
  application:
    name: adapter-config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/middleground
    username: middleground
    password: admin123

mybatis:
  mapper-locations: classpath:/*Mapper.xml
  type-aliases-package: com.geoq.adapter.admin.pojo

swagger:
    title: 数据访问适配器管理
    description: 对数据中台中各数据资产的读写适配器统一管理接口

